eventex/core/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

urlpatterns = patterns('eventex.core.views',
    url(r'^$', 'home', name='home'),
    url(r'^contato/$', 'contato', name='contato'),
    url(r'^sobre/$', 'sobre', name='sobre'),
    url(r'^palestrantes/(?P<slug>[\w-]+)/$', 'speaker_detail', name='speaker_detail'),
    url(r'^palestras/$', 'talk_list', name='talk_list'),
    url(r'^palestras/(?P<pk>\d+)/$', 'talk_detail', name='talk_detail'),
    # url(r'^(.+)/$', 'template_view', name='tpl'),
)

eventex/subscriptions/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

urlpatterns = patterns('eventex.subscriptions.views',
    url(r'^$', 'subscribe', name='subscribe'),
    url(r'^(\d+)/$', 'detail', name='detail'),
)

eventex/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^inscricao/', include('eventex.subscriptions.urls', namespace='subscriptions')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('eventex.core.urls', namespace='core')),
)

eventex/core/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from eventex.core.managers import KindContactManager, PeriodManager

class Speaker(models.Model):
	name = models.CharField(_('Nome'), max_length=255)
	slug = models.SlugField(_('Slug'))
	url = models.URLField(_('Url'))
	description = models.TextField(_(u'Descrição'), blank=True)

	def __unicode__(self):
		return self.name

	@models.permalink
	def get_absolute_url(self):
		return ('core:speaker_detail', (), {'slug': self.slug})

class Contact(models.Model):
	KINDS = (
		('P', _('Telefone')),
		('E', _('E-mail')),
		('F', _('Fax')),
	)

	speaker = models.ForeignKey('Speaker', verbose_name=_('palestrante'))
	kind = models.CharField(_('tipo'), max_length=1, choices=KINDS)
	value = models.CharField(_('valor'), max_length=255)

	objects = models.Manager()
	emails = KindContactManager('E')
	phones = KindContactManager('P')
	faxes = KindContactManager('F')

	def __unicode__(self):
		return self.value

class Talk(models.Model):
    title = models.CharField(_(u'Título'), max_length=200)
    description = models.TextField(_(u'Descrição'))
    start_time = models.TimeField(_(u'Horário'), blank=True)
    speakers = models.ManyToManyField('Speaker', verbose_name=_('palestrantes'))

    objects = PeriodManager()

    class Meta:
    	verbose_name = _('palestra')
    	verbose_name_plural = _('palestras')

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
    	return ('core:talk_detail', (), {'pk': self.pk})

    @property
    def slides(self):
    	return self.media_set.filter(kind='SL')

    @property
    def videos(self):
    	return self.media_set.filter(kind='YT')

# Multi-Table Inheritance
class Course(Talk):
	slots = models.IntegerField(_('vagas'))
	notes = models.TextField(_(u'observações'))

	objects = PeriodManager()

class Media(models.Model):
	MEDIAS = (
		('YT', _('YouTube')),
		('SL', _('SlideShare')),
	)

	talk = models.ForeignKey('Talk', verbose_name=_('palestra'))
	kind = models.CharField(_('tipo'), max_length=2, choices=MEDIAS)
	title = models.CharField(_(u'título'), max_length=255)
	media_id = models.CharField(_('ref'), max_length=255)

	def __unicode__(self):
		return u'%s - %s' % (self.talk.title, self.title)

eventex/core/views.py
# coding: utf-8
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from eventex.core.models import Speaker, Talk

def home(request):
	return render(request, 'index.html')

def contato(request):
	return render(request, 'contato.html')

def sobre(request):
	return render(request, 'sobre.html')

def speaker_detail(request, slug):
	speaker = get_object_or_404(Speaker, slug=slug)
	context = {'speaker': speaker}
	return render(request, 'core/speaker_detail.html', context)

def talk_list(request):
	context = {
		'morning_talks': Talk.objects.at_morning(),
		'afternoon_talks': Talk.objects.at_afternoon(),
	}
	return render(request, 'core/talk_list.html', context)

def talk_detail(request, pk):
	talk = get_object_or_404(Talk, pk=pk)
	context = {'talk': talk,}
	return render(request, 'core/talk_detail.html', context)

#def template_view(request, template_name):
#	return render(request, template_name + '.html')

eventex/core/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/background.css" rel="stylesheet">
    <link rel="shortcut icon" href="{{ STATIC_URL }}img/favicon.gif">
    <style type="text/css">

    /* GLOBAL STYLES
    -------------------------------------------------- */
     Padding below the footer and lighter body text 

    body {
      padding-bottom: 40px;
      color: #5a5a5a;
    }
    </style>

    {% block title %}
      <title>EventeX</title>    
    {% endblock %}

  </head>

  <body>

    <!-- NAVBAR
    ================================================== -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'core:home' %}"><img src="{{ STATIC_URL }}img/logowhite.png" height="18px"></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'core:home' %}">Início</a></li>
            <li><a href="{% url 'core:talk_list' %}">Palestras</a></li>
            <li><a href="{% url 'core:sobre' %}">Sobre</a></li>
            <li><a href="{% url 'core:contato' %}">Contato</a></li>
          </ul>
        </div><!--/.navbar-collapse -->
      </div> <!-- /.container -->
    </div><!-- /.navbar-wrapper -->

    <br>
    <br>
    <br>
    <br>


    {% block content %}
      
    {% endblock %}

    


      <!-- START THE FEATURETTES -->


      <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->


      <!-- FOOTER -->
      <footer>
        <p class="pull-right">
          <a href="#">Voltar ao topo</a>
        </p>
        <p><a href="http://welcometothedjango.com.br/" target="_blank">wttd &copy; 2014</a> &middot; all rights reserved. <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/" target="_blank"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/br/80x15.png" /></a> <a href="http://www.djangoproject.com/" id="django" target="_blank"><img src="http://nedbatchelder.com/pix/django-icon-256.png" border="0" alt="A Django site." title="A Django site." height="20px" /></a> <a href="https://github.com/rg3915/wttd" target="_blank"><img src="{{ STATIC_URL }}img/github_icon20.png" height="25px"></a></p>
      </footer>

    



    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
  </body>
</html>

eventex/core/templates/contato.html
{% extends 'base.html' %}

{% block content %}
	<div class="container">
		<p><span class="glyphicon glyphicon-pencil"></span><a href="mailto:eventex@eventex.com.br"> none@eventex.com.br</a></p>
		<p>Este site é fictício, apenas um teste de aprendizado, portanto o email não é válido.</p>
	</div>
{% endblock %}

eventex/core/templates/index.html
{% extends 'base.html' %}

{% block content %}
      <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron-background">
      <div class="container">
        <h2>Bem-vindo ao EventeX!</h2>
        <p>O evento mais esperado do ano!</p>
        <p><b>Inscrições abertas.</b></p>
        <br>
        <br>
        <button type="button" class="btn btn-lg">
          <span class="glyphicon glyphicon-music"></span><a href="{% url 'subscriptions:subscribe' %}"> Inscreva-se já!</a>
        </button>
      </div>
    </div>
{% endblock %}

eventex/core/templates/sobre.html
{% extends 'base.html' %}

{% block content %}

	<div class="container">
		<p>O EventeX é patrocinado pelo <a href="http://welcometothedjango.com.br/" target="_blank">Welcome to the Django</a>.</p>
	</div>

{% endblock %}